package cba

import (
	"fmt"
	"io"
	"strings"
)

// ExportSQL emits a portable SQL script for the ladder site. Text rather than a
// binary database file on purpose: writing SQLite directly would require a CGO/pure-Go
// driver dependency, and AoE2Kit has none. Piping through the sqlite3 CLI (present both
// locally and on the host) keeps the kit dependency-free, and the same script loads into
// MySQL if the site ever outgrows a file.
//
//	kit cba export --sql > ladder.sql && sqlite3 ladder.db < ladder.sql
//
// The script is idempotent -- it drops and rebuilds every table, because the ladder is
// regenerated wholesale from replays rather than updated incrementally.
func ExportSQL(w io.Writer, c *Corpus, axes []PlayerAxes, names map[int]string) error {
	var b strings.Builder

	b.WriteString("-- CBA ladder, generated by: kit cba export\n")
	b.WriteString("-- Regenerated wholesale; do not hand-edit.\n")
	b.WriteString("BEGIN;\n")

	b.WriteString(`
DROP TABLE IF EXISTS players;
CREATE TABLE players (
  profile_id     INTEGER PRIMARY KEY,
  name           TEXT,
  games          INTEGER NOT NULL DEFAULT 0,
  eco            REAL,
  tempo          REAL,
  combat         REAL,
  verdict        TEXT,
  prod_avg       REAL,
  apm            REAL,
  win_pct        INTEGER,
  decided        INTEGER,
  early_quit_pct INTEGER,
  early_slot_pct INTEGER,
  is_anchor      INTEGER NOT NULL DEFAULT 0,
  is_stacker     INTEGER NOT NULL DEFAULT 0,
  eco_samples    INTEGER NOT NULL DEFAULT 0,
  combat_samples INTEGER NOT NULL DEFAULT 0
);

DROP TABLE IF EXISTS games;
CREATE TABLE games (
  game_id    TEXT PRIMARY KEY,
  scenario   TEXT,
  duration_s INTEGER,
  players    INTEGER
);

DROP TABLE IF EXISTS performances;
CREATE TABLE performances (
  game_id            TEXT NOT NULL,
  profile_id         INTEGER NOT NULL,
  slot               INTEGER,
  team               TEXT,
  civ                TEXT,
  won                INTEGER,
  apm                REAL,
  prod_buildings     INTEGER,
  first_prod_build_s INTEGER,
  own_first_vill_s   INTEGER,
  own_vills          INTEGER,
  own_razes          INTEGER,
  team_first_vill_s  INTEGER,
  team_vills         INTEGER,
  team_razes         INTEGER,
  units_produced     INTEGER,
  units_lost         INTEGER,
  resigned           INTEGER,
  resign_time_s      INTEGER,
  metric_confidence  TEXT,
  PRIMARY KEY (game_id, profile_id)
);
`)

	for i := range c.Games {
		g := &c.Games[i]
		b.WriteString(fmt.Sprintf(
			"INSERT INTO games (game_id,scenario,duration_s,players) VALUES (%s,%s,%d,%d);\n",
			q(g.GameID), q(g.Scenario), g.DurationS, len(g.Rows)))
	}

	for _, r := range c.Rows() {
		// Same filter as ComputeAxes: non-positive ids are unresolved/AI slots, and
		// exporting them would let the site show a phantom player.
		if r.ProfileID <= 0 {
			continue
		}
		b.WriteString(fmt.Sprintf(
			"INSERT OR REPLACE INTO performances VALUES (%s,%d,%d,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s);\n",
			q(r.GameID), r.ProfileID, r.Slot, q(r.Team), q(r.Civ),
			ni(r.Won), nf(r.APM), ni(r.ProdBuildings), ni(r.FirstProdBuildS),
			ni(r.OwnFirstVillS), ni(r.OwnVills), ni(r.OwnRazes),
			ni(r.TeamFirstVillS), ni(r.TeamVills), ni(r.TeamRazes),
			ni(r.UnitsProduced), ni(r.UnitsLost),
			ni(r.Resigned), ni(r.ResignTimeS), q(r.MetricConfidence)))
	}

	for _, p := range axes {
		name := p.Name
		if name == "" {
			name = names[p.ProfileID]
		}
		b.WriteString(fmt.Sprintf(
			"INSERT OR REPLACE INTO players VALUES (%d,%s,%d,%s,%s,%s,%s,%g,%s,%d,%d,%d,%d,%d,%d,%d,%d);\n",
			p.ProfileID, q(name), p.Games,
			optf(p.Eco, p.HasEco), optf(p.Tempo, p.HasTempo), optf(p.Combat, p.HasCombat),
			q(p.Verdict), p.ProdAvg, optf(p.APM, p.APM > 0),
			p.WinPct, p.Decided, p.EarlyQuit, p.EarlySlot,
			bi(p.IsAnchor), bi(p.IsStacker), p.EcoSamples, p.CmbSamples))
	}

	// The site's hot paths are "rank by an axis" and "one player's games".
	b.WriteString(`
CREATE INDEX idx_players_eco     ON players (eco DESC);
CREATE INDEX idx_players_combat  ON players (combat DESC);
CREATE INDEX idx_players_games   ON players (games DESC);
CREATE INDEX idx_perf_profile    ON performances (profile_id);
CREATE INDEX idx_perf_game       ON performances (game_id);
COMMIT;
`)

	_, err := io.WriteString(w, b.String())
	return err
}

// q renders a SQL string literal. Single quotes are doubled -- player names are
// attacker-controlled in the sense that they come from lobby text we do not own.
func q(s string) string {
	if s == "" {
		return "NULL"
	}
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

func ni(p *int) string {
	if p == nil {
		return "NULL"
	}
	return fmt.Sprintf("%d", *p)
}

func nf(p *float64) string {
	if p == nil {
		return "NULL"
	}
	return fmt.Sprintf("%g", *p)
}

func optf(v float64, ok bool) string {
	if !ok {
		return "NULL"
	}
	return fmt.Sprintf("%g", v)
}

func bi(b bool) int {
	if b {
		return 1
	}
	return 0
}
