package replay

import "strings"

func UnitDisplayName(unitID int) string {
	name := knownUnitNames[unitID]
	if name == "" {
		return ""
	}
	return titleUnitName(name)
}

var knownUnitNames = map[int]string{
	4:    "ARCHER",
	5:    "HAND_CANNONEER",
	6:    "ELITE_SKIRMISHER",
	7:    "SKIRMISHER",
	8:    "LONGBOWMAN",
	24:   "CROSSBOWMAN",
	25:   "TEUTONIC_KNIGHT",
	28:   "CHU_KO_NU_DEAD",
	36:   "BOMBARD_CANNON",
	38:   "KNIGHT",
	39:   "CAVALRY_ARCHER",
	40:   "CATAPHRACT",
	41:   "HUSKARL",
	42:   "TREBUCHET",
	46:   "JANISSARY",
	64:   "GATE_SOUTHWEST_TO_NORTHEAST",
	73:   "CHU_KO_NU",
	74:   "MILITIA",
	75:   "MAN_AT_ARMS",
	76:   "HEAVY_SWORDSMAN",
	77:   "LONG_SWORDSMAN",
	82:   "CASTLE",
	83:   "VILLAGER_MALE",
	88:   "GATE_NORTHWEST_TO_SOUTHEAST",
	93:   "SPEARMAN",
	95:   "GATE",
	112:  "FOG_REVEAL_MARKER",
	117:  "STONE_WALL",
	118:  "VILLAGER_MALE_BUILDER",
	125:  "MONK",
	128:  "TRADE_CART_EMPTY",
	155:  "FORTIFIED_WALL",
	156:  "VILLAGER_MALE_REPAIRER",
	207:  "IMPERIAL_CAMEL_RIDER",
	212:  "VILLAGER_FEMALE_BUILDER",
	214:  "VILLAGER_FEMALE_FARMER",
	216:  "VILLAGER_FEMALE_HUNTER",
	218:  "VILLAGER_FEMALE_LUMBERJACK",
	220:  "VILLAGER_FEMALE_STONE_MINER",
	222:  "VILLAGER_FEMALE_REPAIRER",
	234:  "GUARD_TOWER",
	259:  "VILLAGER_MALE_FARMER",
	274:  "FLARE2",
	276:  "WONDER",
	279:  "SCORPION",
	280:  "MANGONEL",
	281:  "THROWING_AXEMAN",
	282:  "MAMELUKE",
	283:  "CAVALIER",
	286:  "MONK_WITH_RELIC",
	291:  "SAMURAI",
	293:  "VILLAGER_FEMALE",
	329:  "CAMEL_RIDER",
	330:  "HEAVY_CAMEL_RIDER",
	331:  "TREBUCHET_PACKED",
	358:  "PIKEMAN",
	359:  "HALBERDIER",
	434:  "KING",
	440:  "PETARD",
	441:  "HUSSAR",
	448:  "SCOUT_CAVALRY",
	473:  "TWO_HANDED_SWORDSMAN",
	474:  "HEAVY_CAVALRY_ARCHER",
	492:  "ARBALESTER",
	493:  "HEAVY_CROSSBOWMAN",
	530:  "ELITE_LONGBOWMAN",
	531:  "ELITE_THROWING_AXEMAN",
	532:  "FAST_FIRE_SHIP",
	533:  "ELITE_LONGBOAT",
	534:  "ELITE_WOAD_RAIDER",
	542:  "HEAVY_SCORPION",
	546:  "LIGHT_CAVALRY",
	548:  "SIEGE_RAM",
	550:  "ONAGER",
	553:  "ELITE_CATAPHRACT",
	554:  "ELITE_TEUTONIC_KNIGHT",
	555:  "ELITE_HUSKARL",
	556:  "ELITE_MAMELUKE",
	557:  "ELITE_JANISSARY",
	558:  "ELITE_WAR_ELEPHANT",
	559:  "ELITE_CHU_KO_NU",
	560:  "ELITE_SAMURAI",
	561:  "ELITE_MANGUDAI",
	567:  "CHAMPION",
	569:  "PALADIN",
	579:  "VILLAGER_MALE_GOLD_MINER",
	581:  "VILLAGER_FEMALE_GOLD_MINER",
	590:  "VILLAGER_FEMALE_SHEPHERD",
	592:  "VILLAGER_MALE_SHEPHERD",
	659:  "GATE_WEST_TO_EAST",
	667:  "GATE_NORTH_TO_SOUTH",
	692:  "BERSERK",
	694:  "ELITE_BERSERK",
	725:  "JAGUAR_WARRIOR",
	726:  "ELITE_JAGUAR_WARRIOR",
	751:  "EAGLE_SCOUT",
	752:  "ELITE_EAGLE_WARRIOR",
	753:  "EAGLE_WARRIOR",
	755:  "TARKAN",
	757:  "ELITE_TARKAN",
	763:  "PLUMED_ARCHER",
	765:  "ELITE_PLUMED_ARCHER",
	771:  "CONQUISTADOR",
	773:  "ELITE_CONQUISTADOR",
	873:  "ELEPHANT_ARCHER",
	875:  "ELITE_ELEPHANT_ARCHER",
	879:  "KAMAYUK",
	881:  "ELITE_KAMAYUK",
	882:  "CONDOTTIERO",
	897:  "CAMEL",
	1007: "CAMEL_ARCHER",
	1009: "ELITE_CAMEL_ARCHER",
	1120: "BALLISTA_ELEPHANT",
	1122: "ELITE_BALLISTA_ELEPHANT",
	1126: "ARAMBAI",
	1128: "ELITE_ARAMBAI",
	1129: "RATTAN_ARCHER",
	1131: "ELITE_RATTAN_ARCHER",
	1132: "BATTLE_ELEPHANT",
	1134: "ELITE_BATTLE_ELEPHANT",
	1155: "IMPERIAL_SKIRMISHER",
	1370: "STEPPE_LANCER",
	1372: "ELITE_STEPPE_LANCER",
	1755: "CAMEL_SCOUT",
	1901: "FIRE_LANCER",
	2333: "VILLAGER_MALE_OYSTER_GATHERER",
	2334: "VILLAGER_FEMALE_OYSTER_GATHERER",
}

func titleUnitName(name string) string {
	parts := strings.Split(strings.ToLower(name), "_")
	for i, part := range parts {
		switch part {
		case "to":
			continue
		case "at", "of":
			if i > 0 {
				continue
			}
		}
		if part == "" {
			continue
		}
		parts[i] = strings.ToUpper(part[:1]) + part[1:]
	}
	return strings.Join(parts, " ")
}
