package campaign

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

type Spec struct {
	SchemaVersion  int     `json:"schema_version"`
	Name           string  `json:"name"`
	WriterScenario string  `json:"writer_scenario"`
	Players        int     `json:"players,omitempty"`
	Fields         []Field `json:"fields"`
}

type Field struct {
	Name      string `json:"name"`
	Type      string `json:"type"`
	PerPlayer bool   `json:"per_player,omitempty"`
	Default   any    `json:"default,omitempty"`
}

type GenerateOptions struct {
	OutDir string
	Prefix string
}

type GenerateReport struct {
	OK             bool     `json:"ok"`
	SpecPath       string   `json:"spec_path"`
	OutDir         string   `json:"out_dir"`
	Name           string   `json:"name"`
	WriterScenario string   `json:"writer_scenario"`
	Files          []string `json:"files"`
	Warnings       []string `json:"warnings,omitempty"`
}

var identRE = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

func LoadSpec(path string) (*Spec, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var spec Spec
	if err := json.Unmarshal(data, &spec); err != nil {
		return nil, fmt.Errorf("%s is not valid campaign spec JSON: %w", path, err)
	}
	return &spec, nil
}

func GenerateFile(path string, opts GenerateOptions) (*GenerateReport, error) {
	spec, err := LoadSpec(path)
	if err != nil {
		return nil, err
	}
	report, err := Generate(spec, opts)
	if report != nil {
		report.SpecPath = path
	}
	return report, err
}

func Generate(spec *Spec, opts GenerateOptions) (*GenerateReport, error) {
	if spec == nil {
		return nil, fmt.Errorf("nil campaign spec")
	}
	if opts.OutDir == "" {
		opts.OutDir = "campaign-out"
	}
	if opts.Prefix == "" {
		opts.Prefix = "A2KCampaign"
	}
	if spec.Players == 0 {
		spec.Players = 8
	}
	report := &GenerateReport{
		OK:             true,
		OutDir:         opts.OutDir,
		Name:           spec.Name,
		WriterScenario: spec.WriterScenario,
	}
	if err := validateSpec(spec, opts.Prefix); err != nil {
		report.OK = false
		return report, err
	}
	if err := os.MkdirAll(opts.OutDir, 0o755); err != nil {
		return nil, err
	}
	files := map[string]string{
		"campaign_writer.xs":      writerXS(spec, opts.Prefix),
		"campaign_reader.xs":      readerXS(spec, opts.Prefix),
		"campaign_manifest.json":  manifestJSON(spec, opts.Prefix),
		"CAMPAIGN_PERSISTENCE.md": notes(spec, opts.Prefix),
	}
	names := make([]string, 0, len(files))
	for name := range files {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		path := filepath.Join(opts.OutDir, name)
		if err := os.WriteFile(path, []byte(files[name]), 0o644); err != nil {
			return nil, err
		}
		report.Files = append(report.Files, path)
	}
	report.Warnings = append(report.Warnings,
		"same-party/same-profile generator only; mixed-party multiplayer re-declare ritual is intentionally not generated in this slice",
		"generated XS source is structure-oriented; engine verification still requires a real writer scenario run followed by a reader scenario run",
	)
	return report, nil
}

func validateSpec(spec *Spec, prefix string) error {
	if strings.TrimSpace(spec.Name) == "" {
		return fmt.Errorf("name is required")
	}
	if strings.TrimSpace(spec.WriterScenario) == "" {
		return fmt.Errorf("writer_scenario is required; use the bare scenario filename stem that xsOpenFile should target")
	}
	if spec.Players < 1 || spec.Players > 8 {
		return fmt.Errorf("players must be 1..8")
	}
	if !identRE.MatchString(prefix) {
		return fmt.Errorf("prefix %q is not a valid XS identifier prefix", prefix)
	}
	seen := map[string]bool{}
	for _, field := range spec.Fields {
		if !identRE.MatchString(field.Name) {
			return fmt.Errorf("field name %q is not a valid XS identifier", field.Name)
		}
		if seen[field.Name] {
			return fmt.Errorf("duplicate field name %q", field.Name)
		}
		seen[field.Name] = true
		switch field.Type {
		case "int", "float", "string":
		default:
			return fmt.Errorf("field %q has unsupported type %q; supported: int, float, string", field.Name, field.Type)
		}
	}
	if len(spec.Fields) == 0 {
		return fmt.Errorf("at least one field is required")
	}
	return nil
}

func writerXS(spec *Spec, prefix string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Generated by kit campaign generate. Same-party writer module.\n")
	fmt.Fprintf(&b, "extern const int %s_VERSION = 1;\n\n", prefix)
	writeGlobals(&b, spec, prefix)
	fmt.Fprintf(&b, "void %sWrite() {\n", prefix)
	fmt.Fprintf(&b, "    bool fileOpen = xsCreateFile(false);\n")
	fmt.Fprintf(&b, "    if (fileOpen == false) {\n")
	fmt.Fprintf(&b, "        xsChatData(\"A2KCAMPAIGN WRITE_OPEN_FAIL\");\n")
	fmt.Fprintf(&b, "        return;\n")
	fmt.Fprintf(&b, "    }\n")
	fmt.Fprintf(&b, "    xsWriteString(\"A2K_CAMPAIGN\");\n")
	fmt.Fprintf(&b, "    xsWriteInt(%s_VERSION);\n", prefix)
	fmt.Fprintf(&b, "    xsWriteString(\"%s\");\n", escapeXS(spec.Name))
	fmt.Fprintf(&b, "    xsWriteInt(%d);\n", persistedValueCount(spec))
	for _, field := range spec.Fields {
		if field.PerPlayer {
			for player := 1; player <= spec.Players; player++ {
				writeXSWrite(&b, field.Type, fmt.Sprintf("%s_p%d_%s", prefix, player, field.Name))
			}
			continue
		}
		writeXSWrite(&b, field.Type, fmt.Sprintf("%s_%s", prefix, field.Name))
	}
	fmt.Fprintf(&b, "    xsWriteString(\"A2K_END\");\n")
	fmt.Fprintf(&b, "    xsChatData(\"A2KCAMPAIGN WRITE_OK\");\n")
	fmt.Fprintf(&b, "}\n")
	return b.String()
}

func readerXS(spec *Spec, prefix string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Generated by kit campaign generate. Same-party reader module.\n")
	fmt.Fprintf(&b, "extern const int %s_VERSION = 1;\n\n", prefix)
	writeGlobals(&b, spec, prefix)
	fmt.Fprintf(&b, "void %sDefaults() {\n", prefix)
	writeDefaultAssignments(&b, spec, prefix)
	fmt.Fprintf(&b, "}\n\n")
	fmt.Fprintf(&b, "bool %sRead() {\n", prefix)
	fmt.Fprintf(&b, "    bool fileOpen = xsOpenFile(\"%s\");\n", escapeXS(spec.WriterScenario))
	fmt.Fprintf(&b, "    if (fileOpen == false) {\n")
	fmt.Fprintf(&b, "        %sDefaults();\n", prefix)
	fmt.Fprintf(&b, "        xsChatData(\"A2KCAMPAIGN READ_MISSING_DEFAULTS\");\n")
	fmt.Fprintf(&b, "        return(false);\n")
	fmt.Fprintf(&b, "    }\n")
	fmt.Fprintf(&b, "    string magic = xsReadString();\n")
	fmt.Fprintf(&b, "    int version = xsReadInt();\n")
	fmt.Fprintf(&b, "    string campaignName = xsReadString();\n")
	fmt.Fprintf(&b, "    int valueCount = xsReadInt();\n")
	fmt.Fprintf(&b, "    if (magic != \"A2K_CAMPAIGN\") {\n")
	fmt.Fprintf(&b, "        %sDefaults();\n", prefix)
	fmt.Fprintf(&b, "        xsChatData(\"A2KCAMPAIGN READ_BAD_MAGIC\");\n")
	fmt.Fprintf(&b, "        return(false);\n")
	fmt.Fprintf(&b, "    }\n")
	fmt.Fprintf(&b, "    if (version != %s_VERSION) {\n", prefix)
	fmt.Fprintf(&b, "        %sDefaults();\n", prefix)
	fmt.Fprintf(&b, "        xsChatData(\"A2KCAMPAIGN READ_BAD_VERSION\");\n")
	fmt.Fprintf(&b, "        return(false);\n")
	fmt.Fprintf(&b, "    }\n")
	fmt.Fprintf(&b, "    if (valueCount != %d) {\n", persistedValueCount(spec))
	fmt.Fprintf(&b, "        %sDefaults();\n", prefix)
	fmt.Fprintf(&b, "        xsChatData(\"A2KCAMPAIGN READ_BAD_COUNT\");\n")
	fmt.Fprintf(&b, "        return(false);\n")
	fmt.Fprintf(&b, "    }\n")
	for _, field := range spec.Fields {
		if field.PerPlayer {
			for player := 1; player <= spec.Players; player++ {
				writeXSRead(&b, field.Type, fmt.Sprintf("%s_p%d_%s", prefix, player, field.Name))
			}
			continue
		}
		writeXSRead(&b, field.Type, fmt.Sprintf("%s_%s", prefix, field.Name))
	}
	fmt.Fprintf(&b, "    string footer = xsReadString();\n")
	fmt.Fprintf(&b, "    if (footer != \"A2K_END\") {\n")
	fmt.Fprintf(&b, "        xsChatData(\"A2KCAMPAIGN READ_BAD_FOOTER\");\n")
	fmt.Fprintf(&b, "        return(false);\n")
	fmt.Fprintf(&b, "    }\n")
	fmt.Fprintf(&b, "    xsChatData(\"A2KCAMPAIGN READ_OK\");\n")
	fmt.Fprintf(&b, "    return(true);\n")
	fmt.Fprintf(&b, "}\n")
	return b.String()
}

func writeGlobals(b *strings.Builder, spec *Spec, prefix string) {
	for _, field := range spec.Fields {
		if field.PerPlayer {
			for player := 1; player <= spec.Players; player++ {
				fmt.Fprintf(b, "%s %s_p%d_%s = %s;\n", field.Type, prefix, player, field.Name, defaultValue(field))
			}
			continue
		}
		fmt.Fprintf(b, "%s %s_%s = %s;\n", field.Type, prefix, field.Name, defaultValue(field))
	}
	fmt.Fprintln(b)
}

func writeDefaultAssignments(b *strings.Builder, spec *Spec, prefix string) {
	for _, field := range spec.Fields {
		if field.PerPlayer {
			for player := 1; player <= spec.Players; player++ {
				fmt.Fprintf(b, "    %s_p%d_%s = %s;\n", prefix, player, field.Name, defaultValue(field))
			}
			continue
		}
		fmt.Fprintf(b, "    %s_%s = %s;\n", prefix, field.Name, defaultValue(field))
	}
}

func writeXSWrite(b *strings.Builder, typ string, name string) {
	switch typ {
	case "int":
		fmt.Fprintf(b, "    xsWriteInt(%s);\n", name)
	case "float":
		fmt.Fprintf(b, "    xsWriteFloat(%s);\n", name)
	case "string":
		fmt.Fprintf(b, "    xsWriteString(%s);\n", name)
	}
}

func writeXSRead(b *strings.Builder, typ string, name string) {
	switch typ {
	case "int":
		fmt.Fprintf(b, "    %s = xsReadInt();\n", name)
	case "float":
		fmt.Fprintf(b, "    %s = xsReadFloat();\n", name)
	case "string":
		fmt.Fprintf(b, "    %s = xsReadString();\n", name)
	}
}

func persistedValueCount(spec *Spec) int {
	count := 0
	for _, field := range spec.Fields {
		if field.PerPlayer {
			count += spec.Players
		} else {
			count++
		}
	}
	return count
}

func defaultValue(field Field) string {
	if field.Default == nil {
		switch field.Type {
		case "string":
			return "\"\""
		case "float":
			return "0.0"
		default:
			return "0"
		}
	}
	switch field.Type {
	case "string":
		return fmt.Sprintf("\"%s\"", escapeXS(fmt.Sprint(field.Default)))
	case "float":
		return fmt.Sprint(field.Default)
	default:
		return fmt.Sprintf("%.0f", numericDefault(field.Default))
	}
}

func numericDefault(value any) float64 {
	switch v := value.(type) {
	case float64:
		return v
	case int:
		return float64(v)
	default:
		return 0
	}
}

func manifestJSON(spec *Spec, prefix string) string {
	type manifest struct {
		SchemaVersion  int      `json:"schema_version"`
		Name           string   `json:"name"`
		Mode           string   `json:"mode"`
		WriterScenario string   `json:"writer_scenario"`
		ReaderOpens    string   `json:"reader_opens"`
		Prefix         string   `json:"prefix"`
		Players        int      `json:"players"`
		Fields         []Field  `json:"fields"`
		Calls          []string `json:"script_calls"`
	}
	data, _ := json.MarshalIndent(manifest{
		SchemaVersion:  1,
		Name:           spec.Name,
		Mode:           "same_party_same_profile_xsdat",
		WriterScenario: spec.WriterScenario,
		ReaderOpens:    spec.WriterScenario,
		Prefix:         prefix,
		Players:        spec.Players,
		Fields:         spec.Fields,
		Calls:          []string{prefix + "Write();", prefix + "Read();", prefix + "Defaults();"},
	}, "", "  ")
	return string(data) + "\n"
}

func notes(spec *Spec, prefix string) string {
	return fmt.Sprintf(`# Campaign Persistence

Generated by kit campaign generate.

Mode: same-party / same-profile .xsdat persistence.

Writer scenario stem: %s

Reader call: xsOpenFile("%s")

Script calls to wire from triggers:

- Writer/save point: %sWrite();
- Reader/load point: %sRead();
- Explicit defaults/reset: %sDefaults();

This uses the engine-verified v9 rule: cross-scenario reads use the writer
scenario's bare stem and do not include .xsdat.

This slice intentionally does not generate mixed-party multiplayer re-declare
ritual triggers. For multiplayer campaign continuity, every human must re-enter
state through synchronized in-game declarations before scenario logic trusts it.

Engine verification still requires:

1. Run the writer scenario and let it call %sWrite();.
2. Without deleting the sidecar, run the reader scenario in the same profile.
3. Confirm A2KCAMPAIGN READ_OK appears in replay chat or sidecar evidence.
`, spec.WriterScenario, spec.WriterScenario, prefix, prefix, prefix, prefix)
}

func escapeXS(value string) string {
	value = strings.ReplaceAll(value, `\`, `\\`)
	return strings.ReplaceAll(value, `"`, `\"`)
}
