package main

// Command traits, declared beside the dispatch they describe.
//
// Bootstrapped once by "apiref --emit-catalog"; maintained here by hand.
// TestCommandCatalogCoversUsage fails if a command in usage() has no entry, so
// adding a command to the CLI forces a decision about what it does.
//
//	trait: read_only writes files/registries, or performs network I/O.
//	input: the kind of file the command consumes, so tooling need not guess.

type CommandSpec struct {
	Name  string `json:"name"`
	Usage string `json:"usage"`
	Trait string `json:"trait"`
	Input string `json:"input"`
}

const (
	TraitReadOnly = "read_only"
	TraitWrites   = "writes"
	TraitNetwork  = "network"
)

var commandCatalog = []CommandSpec{
	{Name: "ai diff", Usage: "kit ai diff <before-file-or-folder> <after-file-or-folder> [--text]", Trait: TraitReadOnly, Input: "other"},
	{Name: "ai fingerprint", Usage: "kit ai fingerprint <file-or-folder> [--registry known_ais.json] [--register NAME] [--signature AI_FILES_SIGNATURE]", Trait: TraitWrites, Input: "other"},
	{Name: "ai lint", Usage: "kit ai lint <file-or-folder> [--text]", Trait: TraitReadOnly, Input: "other"},
	{Name: "campaign", Usage: "kit campaign <generate> ...", Trait: TraitReadOnly, Input: "other"},
	{Name: "campaign generate", Usage: "kit campaign generate <campaign.json> [--out-dir DIR] [--prefix A2KCampaign] [--text]", Trait: TraitWrites, Input: "other"},
	{Name: "cba replay", Usage: "kit cba replay <progression|razes|raze-pressure|phases|perf|doctrine> <file.aoe2record|replay.zip> [--dat <empires2_x2_p1.dat>] [--text|--json]", Trait: TraitReadOnly, Input: "group"},
	{Name: "cba balance", Usage: "kit cba balance [--text|--json]", Trait: TraitReadOnly, Input: "none"},
	{Name: "cba sidechannels", Usage: "kit cba sidechannels <file.aoe2record|replay.zip> [--text]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "cba phase-facts", Usage: "kit cba phase-facts <file.aoe2record|replay.zip> --dat <empires2_x2_p1.dat> [--text]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "cba trigger-razes", Usage: "kit cba trigger-razes <file.aoe2record|replay.zip> [--dat <empires2_x2_p1.dat>] [--text]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "cba trigger-spawns", Usage: "kit cba trigger-spawns <file.aoe2record|replay.zip> [--dat <empires2_x2_p1.dat>] [--text]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "cba registry", Usage: "kit cba registry <replay|dir>... [--out <file.json>] [--text]", Trait: TraitWrites, Input: "replay"},
	{Name: "cba ingest", Usage: "kit cba ingest --corpus <file.jsonl> (--registry <file.json>|--unverified <replay|dir>...) [--force] [--limit N]", Trait: TraitWrites, Input: "replay"},
	{Name: "cba archive", Usage: "kit cba archive --queue <q.json> --out <dir> --max N [--delay-ms MS] [--manifest f.jsonl]", Trait: TraitNetwork, Input: "other"},
	{Name: "cba axes", Usage: "kit cba axes --corpus <file.jsonl> [--min-games N] [--names <file.json>] [--text]", Trait: TraitReadOnly, Input: "other"},
	{Name: "cba export", Usage: "kit cba export --corpus <file.jsonl> [--names <file.json>] [--sql]", Trait: TraitReadOnly, Input: "other"},
	{Name: "ci", Usage: "kit ci <init|check> ...", Trait: TraitReadOnly, Input: "group"},
	{Name: "ci check", Usage: "kit ci check [aoe2kit-ci.json] [--text]", Trait: TraitReadOnly, Input: "other"},
	{Name: "ci init", Usage: "kit ci init [scenario.aoe2scenario] [--root DIR] [--overwrite] [--text]", Trait: TraitWrites, Input: "scenario"},
	{Name: "collect", Usage: "kit collect <folder> [--registry known_scenarios.json] [--dry-run]", Trait: TraitWrites, Input: "folder"},
	{Name: "dat", Usage: "kit dat <info|check|roundtrip|codec-plan|codec-patch|delete-plan|delete|plan|patch|...> <empires*.dat>", Trait: TraitReadOnly, Input: "dat"},
	{Name: "dat abilities", Usage: "kit dat abilities <empires*.dat> [--limit N|--all] [--name-contains TEXT] [--effect-id N] [--command-type N] [--operand N]", Trait: TraitReadOnly, Input: "dat"},
	{Name: "dat ability", Usage: "kit dat ability <empires*.dat> <tech_id>", Trait: TraitReadOnly, Input: "dat"},
	{Name: "dat ability-create", Usage: "kit dat ability-create <in.dat> <out.dat> --from-tech N --name TEXT [--effect-name TEXT] [--from-effect N] [--command type,a,b,c,d|json] [--append-command type,a,b,c,d|json] [tech flags]", Trait: TraitWrites, Input: "dat"},
	{Name: "dat ability-delete", Usage: "kit dat ability-delete <in.dat> <out.dat> <tech_id>", Trait: TraitWrites, Input: "dat"},
	{Name: "dat ability-disable", Usage: "kit dat ability-disable <in.dat> <out.dat> <tech_id>", Trait: TraitWrites, Input: "dat"},
	{Name: "dat ability-patch", Usage: "kit dat ability-patch <in.dat> <out.dat> <tech_id> [--name TEXT] [--effect-name TEXT] [--clear-commands] [--command type,a,b,c,d|json] [--append-command type,a,b,c,d|json] [--remove-command N] [tech flags]", Trait: TraitWrites, Input: "dat"},
	{Name: "dat availability", Usage: "kit dat availability <empires*.dat> <unit_id> [--civ N|--all-civs]", Trait: TraitReadOnly, Input: "dat"},
	{Name: "dat availability-set", Usage: "kit dat availability-set <in.dat> <out.dat> <unit_id> (--civ N|--all-civs) --enabled true|false|1|0", Trait: TraitWrites, Input: "dat"},
	{Name: "dat civ-patch", Usage: "kit dat civ-patch <in.dat> <out.dat> <civ_id> [--name TEXT] [--tech-tree-id N] [--team-bonus-id N] [--icon-set N] [--resource INDEX,VALUE]", Trait: TraitWrites, Input: "dat"},
	{Name: "dat civs", Usage: "kit dat civs <empires*.dat>", Trait: TraitReadOnly, Input: "dat"},
	{Name: "dat codec-patch", Usage: "kit dat codec-patch <in.dat> <out.dat> --recipe recipe.json", Trait: TraitWrites, Input: "dat"},
	{Name: "dat codec-plan", Usage: "kit dat codec-plan <in.dat> --recipe recipe.json", Trait: TraitWrites, Input: "dat"},
	{Name: "dat command-matrix", Usage: "kit dat command-matrix <empires*.dat> [--limit examples_per_type|--all] [--command-type N] [--reference-kind unit|tech] [--reference-field FIELD] [--typed-only|--unknown-only|--candidate-only] [--text|--json]", Trait: TraitReadOnly, Input: "dat"},
	{Name: "dat delete-plan", Usage: "kit dat delete-plan <in.dat> <section|effect-command|sound-item|graphic-row-kind|unit-header-task|unit-row-kind> <target> [--civ N|--all-civs] [--text]", Trait: TraitReadOnly, Input: "dat"},
	{Name: "dat delete", Usage: "kit dat delete <in.dat> <out.dat> <section|effect-command|sound-item|graphic-row-kind|unit-header-task|unit-row-kind> <target> [--civ N|--all-civs]", Trait: TraitWrites, Input: "dat"},
	{Name: "dat disconnect", Usage: "kit dat disconnect <in.dat> <out.dat> <tech|unit> <id>", Trait: TraitWrites, Input: "dat"},
	{Name: "dat diff", Usage: "kit dat diff <base.dat> <mod.dat> [--section NAME|all] [--limit N|--all] [--text|--json]", Trait: TraitReadOnly, Input: "dat"},
	{Name: "dat effect", Usage: "kit dat effect <empires*.dat> <effect_id>", Trait: TraitReadOnly, Input: "dat"},
	{Name: "dat effect-command-delete", Usage: "kit dat effect-command-delete <in.dat> <out.dat> <effect_id> <command_index>", Trait: TraitWrites, Input: "dat"},
	{Name: "dat effect-create", Usage: "kit dat effect-create <in.dat> <out.dat> --name TEXT [--from-effect N] [--command type,a,b,c,d|json] [--append-command type,a,b,c,d|json] [--remove-command N]", Trait: TraitWrites, Input: "dat"},
	{Name: "dat effect-delete", Usage: "kit dat effect-delete <in.dat> <out.dat> <effect_id>", Trait: TraitWrites, Input: "dat"},
	{Name: "dat effect-disable", Usage: "kit dat effect-disable <in.dat> <out.dat> <effect_id>", Trait: TraitWrites, Input: "dat"},
	{Name: "dat effect-explain", Usage: "kit dat effect-explain <empires*.dat> <effect_id> [--text|--json]", Trait: TraitReadOnly, Input: "dat"},
	{Name: "dat effect-patch", Usage: "kit dat effect-patch <in.dat> <out.dat> <effect_id> [--name TEXT] [--clear-commands] [--command type,a,b,c,d|json] [--append-command type,a,b,c,d|json] [--remove-command N]", Trait: TraitWrites, Input: "dat"},
	{Name: "dat effects", Usage: "kit dat effects <empires*.dat> [--limit N|--all] [--command-type N] [--operand N]", Trait: TraitReadOnly, Input: "dat"},
	{Name: "dat graphic", Usage: "kit dat graphic <empires*.dat> <graphic_id> [--spans|--raw]", Trait: TraitReadOnly, Input: "dat"},
	{Name: "dat graphic-angle-sound-delete", Usage: "kit dat graphic-angle-sound-delete <in.dat> <out.dat> <graphic_id> <row_index>", Trait: TraitWrites, Input: "dat"},
	{Name: "dat graphic-create", Usage: "kit dat graphic-create <in.dat> <out.dat> --from N [graphic scalar flags]", Trait: TraitWrites, Input: "dat"},
	{Name: "dat graphic-delta-delete", Usage: "kit dat graphic-delta-delete <in.dat> <out.dat> <graphic_id> <row_index>", Trait: TraitWrites, Input: "dat"},
	{Name: "dat graphic-patch", Usage: "kit dat graphic-patch <in.dat> <out.dat> <graphic_id> [graphic scalar flags]", Trait: TraitWrites, Input: "dat"},
	{Name: "dat graphics", Usage: "kit dat graphics <empires*.dat> [--limit N|--all] [--particle] [--name-contains TEXT] [--spans|--raw]", Trait: TraitReadOnly, Input: "dat"},
	{Name: "dat palette", Usage: "kit dat palette <empires*.dat> [--id N] [--min-variants N] [--json|--text]", Trait: TraitReadOnly, Input: "dat"},
	{Name: "dat patch", Usage: "kit dat patch <in.dat> <out.dat> --recipe recipe.json", Trait: TraitWrites, Input: "dat"},
	{Name: "dat patch-graphic", Usage: "kit dat patch-graphic <in.dat> <out.dat> <graphic_id> [graphic scalar flags]", Trait: TraitWrites, Input: "dat"},
	{Name: "dat patch-unit", Usage: "kit dat patch-unit <in.dat> <out.dat> <civ_id> <unit_id> [scalar flags] [--type50-attack I,field=value] [--cost I,field=value] [--task I,field=value]", Trait: TraitWrites, Input: "dat"},
	{Name: "dat plan", Usage: "kit dat plan <in.dat> --recipe recipe.json", Trait: TraitWrites, Input: "dat"},
	{Name: "dat player-colours", Usage: "kit dat player-colours <empires*.dat>", Trait: TraitReadOnly, Input: "dat"},
	{Name: "dat player-colour-create", Usage: "kit dat player-colour-create <in.dat> <out.dat> --from N [colour-flags]", Trait: TraitWrites, Input: "dat"},
	{Name: "dat player-colour-delete", Usage: "kit dat player-colour-delete <in.dat> <out.dat> <colour_id>", Trait: TraitWrites, Input: "dat"},
	{Name: "dat player-colour-patch", Usage: "kit dat player-colour-patch <in.dat> <out.dat> <colour_id> [colour-flags]", Trait: TraitWrites, Input: "dat"},
	{Name: "dat random-maps", Usage: "kit dat random-maps <empires*.dat>", Trait: TraitReadOnly, Input: "dat"},
	{Name: "dat refs", Usage: "kit dat refs <in.dat> <section> <id> [--class CLASS] [--confidence NAME] [--source-section SECTION] [--limit N] [--text|--json]", Trait: TraitReadOnly, Input: "dat"},
	{Name: "dat semantics-pack", Usage: "kit dat semantics-pack <in.dat> <out-dir> [--feature full|local-building-effects]", Trait: TraitWrites, Input: "dat"},
	{Name: "dat semantics-readback", Usage: "kit dat semantics-readback <expected.json> --dat empires*.dat --scenario file.aoe2scenario --replay file.aoe2record [--out report.md] [--text]", Trait: TraitWrites, Input: "dat"},
	{Name: "dat sound", Usage: "kit dat sound <empires*.dat> <sound_id>", Trait: TraitReadOnly, Input: "dat"},
	{Name: "dat sound-create", Usage: "kit dat sound-create <in.dat> <out.dat> --from N [sound-flags] [--item file,resource,probability,civ,icon_set]", Trait: TraitWrites, Input: "dat"},
	{Name: "dat sound-delete", Usage: "kit dat sound-delete <in.dat> <out.dat> <sound_id>", Trait: TraitWrites, Input: "dat"},
	{Name: "dat sound-item-delete", Usage: "kit dat sound-item-delete <in.dat> <out.dat> <sound_id> <item_index>", Trait: TraitWrites, Input: "dat"},
	{Name: "dat sound-patch", Usage: "kit dat sound-patch <in.dat> <out.dat> <sound_id> [sound-flags] [--item INDEX,field=value...] [--remove-item N]", Trait: TraitWrites, Input: "dat"},
	{Name: "dat sounds", Usage: "kit dat sounds <empires*.dat> [--limit N|--all]", Trait: TraitReadOnly, Input: "dat"},
	{Name: "dat spans", Usage: "kit dat spans <empires*.dat>", Trait: TraitReadOnly, Input: "dat"},
	{Name: "dat tech", Usage: "kit dat tech <empires*.dat> <tech_id>", Trait: TraitReadOnly, Input: "dat"},
	{Name: "dat tech-create", Usage: "kit dat tech-create <in.dat> <out.dat> --from N [tech-flags]", Trait: TraitWrites, Input: "dat"},
	{Name: "dat tech-delete", Usage: "kit dat tech-delete <in.dat> <out.dat> <tech_id>", Trait: TraitWrites, Input: "dat"},
	{Name: "dat tech-explain", Usage: "kit dat tech-explain <empires*.dat> <tech_id> [--text|--json]", Trait: TraitReadOnly, Input: "dat"},
	{Name: "dat tech-patch", Usage: "kit dat tech-patch <in.dat> <out.dat> <tech_id> [tech-flags]", Trait: TraitWrites, Input: "dat"},
	{Name: "dat tech-tree", Usage: "kit dat tech-tree <empires*.dat> [--full]", Trait: TraitReadOnly, Input: "dat"},
	{Name: "dat tech-tree-connection-create", Usage: "kit dat tech-tree-connection-create <in.dat> <out.dat> <building|unit|research> <from_index> [connection flags]", Trait: TraitWrites, Input: "dat"},
	{Name: "dat tech-tree-connection-delete", Usage: "kit dat tech-tree-connection-delete <in.dat> <out.dat> <building|unit|research> <index>", Trait: TraitWrites, Input: "dat"},
	{Name: "dat tech-tree-connection-patch", Usage: "kit dat tech-tree-connection-patch <in.dat> <out.dat> <building|unit|research> <index> [connection flags]", Trait: TraitWrites, Input: "dat"},
	{Name: "dat techs", Usage: "kit dat techs <empires*.dat> [--limit N|--all] [--name-contains TEXT]", Trait: TraitReadOnly, Input: "dat"},
	{Name: "dat terrain", Usage: "kit dat terrain <empires*.dat> <terrain_id>", Trait: TraitReadOnly, Input: "dat"},
	{Name: "dat terrain-patch", Usage: "kit dat terrain-patch <in.dat> <out.dat> <terrain_id> [--name TEXT] [--name-2 TEXT] [--overlay-mask-name TEXT]", Trait: TraitWrites, Input: "dat"},
	{Name: "dat terrain-restriction-patch", Usage: "kit dat terrain-restriction-patch <in.dat> <out.dat> <restriction_id> --terrain TERRAIN_ID,PASSABILITY", Trait: TraitWrites, Input: "dat"},
	{Name: "dat terrain-restrictions", Usage: "kit dat terrain-restrictions <empires*.dat> [--limit N|--all]", Trait: TraitReadOnly, Input: "dat"},
	{Name: "dat terrains", Usage: "kit dat terrains <empires*.dat> [--limit N|--all]", Trait: TraitReadOnly, Input: "dat"},
	{Name: "dat unit", Usage: "kit dat unit <empires*.dat> <civ_id> <unit_id>", Trait: TraitReadOnly, Input: "dat"},
	{Name: "dat unit-child-delete", Usage: "kit dat unit-child-delete <in.dat> <out.dat> <damage-graphic|attack|armour|train-location|drop-site|task> <civ_id> <unit_id> <row_index>", Trait: TraitWrites, Input: "dat"},
	{Name: "dat unit-create", Usage: "kit dat unit-create <in.dat> <out.dat> --from-civ N --from-unit N (--civ N|--all-civs) [unit patch flags]", Trait: TraitWrites, Input: "dat"},
	{Name: "dat unit-delete", Usage: "kit dat unit-delete <in.dat> <out.dat> <unit_id> (--civ N|--all-civs)", Trait: TraitWrites, Input: "dat"},
	{Name: "dat unit-header", Usage: "kit dat unit-header <empires*.dat> <header_id>", Trait: TraitReadOnly, Input: "dat"},
	{Name: "dat unit-header-task-delete", Usage: "kit dat unit-header-task-delete <in.dat> <out.dat> <unit_header_id> <task_index>", Trait: TraitWrites, Input: "dat"},
	{Name: "dat unit-headers", Usage: "kit dat unit-headers <empires*.dat> [--limit N|--all]", Trait: TraitReadOnly, Input: "dat"},
	{Name: "dat units", Usage: "kit dat units <empires*.dat> [--civ N] [--id N] [--name TEXT|--name-contains TEXT] [--class building|unit|creatable] [--limit N|--all] [--json]", Trait: TraitReadOnly, Input: "dat"},
	{Name: "credits", Usage: "kit credits [notice] [folder] [--text|--json]", Trait: TraitReadOnly, Input: "folder"},
	{Name: "doctor", Usage: "kit doctor", Trait: TraitReadOnly, Input: "none"},
	{Name: "docs", Usage: "kit docs <lint> ...", Trait: TraitReadOnly, Input: "group"},
	{Name: "docs lint", Usage: "kit docs lint [folder] [--text|--json]", Trait: TraitReadOnly, Input: "folder"},
	{Name: "facts", Usage: "kit facts <list|check> [--include-provisional] [--domain DOMAIN] [--text]", Trait: TraitReadOnly, Input: "group"},
	{Name: "fx bind", Usage: "kit fx bind --atlas file.png|--dds file.dds --grid RxC|--frames N --frame-size WxH --into resources/_common --dat empires*.dat --unit N --slot flying|standing|attack|dying --from graphic_id --name fx_name [--dry-run]", Trait: TraitWrites, Input: "dat"},
	{Name: "fx lint", Usage: "kit fx lint <mod-or-resources/_common> [--dat empires*.dat] [--text]", Trait: TraitReadOnly, Input: "dat"},
	{Name: "fx new", Usage: "kit fx new <name> --preset trail|explosion|aura|projectile-fire [--grid RxC] [descriptor overrides]", Trait: TraitWrites, Input: "other"},
	{Name: "gfx export", Usage: "kit gfx export <file.sld> [--out dir] [--limit N] [--text]", Trait: TraitWrites, Input: "other"},
	{Name: "gfx info", Usage: "kit gfx info <file.sld> [--text]", Trait: TraitReadOnly, Input: "other"},
	{Name: "identify", Usage: "kit identify <file.aoe2scenario|file.aoe2record> [--registry known_scenarios.json] [--ai-registry known_ais.json] [--register NAME] [--family FAMILY] [--description TEXT]", Trait: TraitReadOnly, Input: "scenario"},
	{Name: "inventory", Usage: "kit inventory [folder]", Trait: TraitReadOnly, Input: "folder"},
	{Name: "manifest", Usage: "kit manifest", Trait: TraitReadOnly, Input: "none"},
	{Name: "mod", Usage: "kit mod <check|inspect> <moddir> [--status mod-status.json]", Trait: TraitReadOnly, Input: "group"},
	{Name: "pack", Usage: "kit pack [out.zip] [folder] [--profile full|handoff|sandbox|public]", Trait: TraitWrites, Input: "folder"},
	{Name: "player stats", Usage: "kit player stats <profileId> [--match-type N] [--cache-dir DIR] [--force] [--text]", Trait: TraitNetwork, Input: "other"},
	{Name: "portable-check", Usage: "kit portable-check [folder] [--profile full|handoff|sandbox|public]", Trait: TraitReadOnly, Input: "folder"},
	{Name: "project", Usage: "kit project <inspect|snapshot|diff|lineage> ...", Trait: TraitReadOnly, Input: "group"},
	{Name: "project inspect", Usage: "kit project inspect [folder] [--limit N] [--text|--json]", Trait: TraitReadOnly, Input: "folder"},
	{Name: "project snapshot", Usage: "kit project snapshot [folder] --out project-snapshot.json [--text|--json]", Trait: TraitWrites, Input: "folder"},
	{Name: "project diff", Usage: "kit project diff <before-snapshot.json> <after-snapshot.json> [--limit N] [--text|--json]", Trait: TraitReadOnly, Input: "other"},
	{Name: "project lineage", Usage: "kit project lineage --input PATH --output PATH [--input PATH...] [--output PATH...] [--tool TEXT] [--note TEXT] [--manifest lineage.json] [--text|--json]", Trait: TraitWrites, Input: "other"},
	{Name: "recipe", Usage: "kit recipe <list|show|export> ...", Trait: TraitReadOnly, Input: "none"},
	{Name: "recipe export", Usage: "kit recipe export <out-dir> [--domain scenario|dat|all] [--force] [--text|--json]", Trait: TraitWrites, Input: "other"},
	{Name: "recipe list", Usage: "kit recipe list [--domain scenario|dat|all] [--text|--json]", Trait: TraitReadOnly, Input: "none"},
	{Name: "recipe show", Usage: "kit recipe show <name> [--recipe-only] [--text|--json]", Trait: TraitReadOnly, Input: "none"},
	{Name: "release-check", Usage: "kit release-check <scenario.aoe2scenario> [--previous old.aoe2scenario] [--mod moddir] [--status mod-status.json] [--pack out.zip] [--text]", Trait: TraitWrites, Input: "scenario"},
	{Name: "roadmap", Usage: "kit roadmap <crud|rwd|dark> [--domain scenario|dat|replay|all] [--text|--json]", Trait: TraitReadOnly, Input: "none"},
	{Name: "roadmap crud", Usage: "kit roadmap crud [--domain scenario|dat|replay|all] [--text|--json]", Trait: TraitReadOnly, Input: "none"},
	{Name: "roadmap dark", Usage: "kit roadmap dark [--domain scenario|dat|replay|all] [--text|--json]", Trait: TraitReadOnly, Input: "none"},
	{Name: "roadmap rwd", Usage: "kit roadmap rwd [--domain scenario|dat|replay|all] [--text|--json]", Trait: TraitReadOnly, Input: "none"},
	{Name: "replay", Usage: "kit replay <info|summary|graph|triggers|trigger-neighborhood|coverage|opaque-spans|frontier|corpus|opaque-clusters|ai-manifest|effective-data|effective-units|datamod-check|fetch|diff-state|scan-value|header-anchors|objects|object-state|object-shapes|spawns|lifecycle|postgame|camera|sync|sync-log|checksum-phase|checksum-probe|combat|deaths|player-series|playtest|carrier|sidecar-sync|xs-telemetry|events|actions|player-events|chat|feedback|story|player-profile|inbox|telemetry|issues|unknowns> <path>", Trait: TraitReadOnly, Input: "group"},
	{Name: "replay actions", Usage: "kit replay actions <file.aoe2record> [--action-id N] [--limit N] [--objects] [--raw] [--text|--json]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay ai-manifest", Usage: "kit replay ai-manifest <file.aoe2record> [--promisory-root DIR] [--text]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay carrier", Usage: "kit replay carrier <file.aoe2record> --ledger expected.json [--text|--json]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay chat", Usage: "kit replay chat <file.aoe2record> [--text|--json]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay checksum-phase", Usage: "kit replay checksum-phase <file.aoe2record> [--word N|--all-words] [--player N] [--text|--json]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay checksum-probe", Usage: "kit replay checksum-probe <file.aoe2record> [--preset v6-playground-helper|v7-checksum-calibration] [--player N] [--object-count-delta N] [--unit-type-sum-delta N] [--object-id-sum-delta N] [--state-sum-delta N] [--carry-sum-delta N] [--digest-delta N] [--limit N] [--text|--json]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay combat", Usage: "kit replay combat <file.aoe2record> [--window-ms N] [--min-net-loss N] [--limit N] [--sort loss|time] [--text|--json]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay deaths", Usage: "kit replay deaths <file.aoe2record> [--limit N] [--text|--json]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay corpus", Usage: "kit replay corpus <folder-or-replay> [--flat] [--no-zip] [--unknown-samples N] [--text]", Trait: TraitReadOnly, Input: "folder"},
	{Name: "replay coverage", Usage: "kit replay coverage <file.aoe2record> [--text|--json] [--fail-on-opaque]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay datamod-check", Usage: "kit replay datamod-check <file.aoe2record> [--baseline-replay baseline.aoe2record] [--dat empires2_x2_p1.dat] [--known-template SHA256] [--tail-offset N] [--count N] [--limit N] [--text]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay diff-state", Usage: "kit replay diff-state <before.aoe2record> <after.aoe2record> [--focus all|opaque] [--limit N] [--text]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay diff-triggers", Usage: "kit replay diff-triggers <before.aoe2record|zip> <after.aoe2record|zip> [--limit N] [--text]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay effective-data", Usage: "kit replay effective-data <file.aoe2record> [--dat empires2_x2_p1.dat] [--player N] [--tail-offset N] [--count N] [--limit N] [--known-template SHA256] [--all] [--text|--tree]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay effective-units", Usage: "kit replay effective-units <file.aoe2record> --dat empires2_x2_p1.dat [--player N] [--limit N] [--include-unchanged] [--all-types] [--include-duplicates] [--text]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay events", Usage: "kit replay events <file.aoe2record> [--all] [--system] [--untyped-actions] [--objects] [--raw] [--context context.json] [--text]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay feedback", Usage: "kit replay feedback <file.aoe2record> [--text]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay fetch", Usage: "kit replay fetch <gameId> --all-povs --from-roster <replay.aoe2record|zip> [--out dir] [--force] [--text]", Trait: TraitNetwork, Input: "replay"},
	{Name: "replay frontier", Usage: "kit replay frontier <file.aoe2record> [--min-duplicate-bytes N] [--limit N] [--text|--json]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay header-anchors", Usage: "kit replay header-anchors <file.aoe2record> [--limit N] [--text|--json]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay info", Usage: "kit replay info <file.aoe2record|zip> [--text|--json] [--tiles] [--full]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay inbox", Usage: "kit replay inbox <folder> [--context context.json] [--text]", Trait: TraitReadOnly, Input: "folder"},
	{Name: "replay issues", Usage: "kit replay issues <file.aoe2record> [--context context.json] [--text]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay lifecycle", Usage: "kit replay lifecycle <file.aoe2record> [--text]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay object-shapes", Usage: "kit replay object-shapes <file.aoe2record> [--referenced] [--limit N] [--text]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay object-state", Usage: "kit replay object-state <file.aoe2record> [--referenced] [--class CLASS] [--limit N] [--text]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay objects", Usage: "kit replay objects <file.aoe2record> [--referenced] [--limit N] [--text]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay opaque-clusters", Usage: "kit replay opaque-clusters <folder-or-replay> [--space inflated_header|body] [--min-bytes N] [--limit N] [--samples N] [--flat] [--no-zip] [--text]", Trait: TraitReadOnly, Input: "folder"},
	{Name: "replay opaque-spans", Usage: "kit replay opaque-spans <file.aoe2record> [--space inflated_header|body] [--min-bytes N] [--limit N] [--text]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay player-events", Usage: "kit replay player-events <file.aoe2record> [--player N] [--type TYPE] [--action-id N] [--phase PHASE] [--from TIME] [--to TIME] [--limit N] [--objects] [--raw] [--text]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay player-profile", Usage: "kit replay player-profile <file.aoe2record> [--context context.json] [--window-sec N] [--dead-gap-sec N] [--cell-size N] [--include-events] [--text|--json]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay player-series", Usage: "kit replay player-series <file.aoe2record> [--player N] [--changes-only] [--limit N] [--text|--json]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay playtest", Usage: "kit replay playtest <file.aoe2record> [--window N] [--include-computers] [--text|--json]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay postgame", Usage: "kit replay postgame <file.aoe2record> [--text]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay scan-value", Usage: "kit replay scan-value <file.aoe2record> [--value N] [--width 8|16|32|64] [--hex BYTES] [--string TEXT] [--space inflated_header|body] [--limit N] [--text]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay sidecar-sync", Usage: "kit replay sidecar-sync <file.aoe2record> --xsdat run.xsdat (--ledger expected.json|--schema rtv12|rtv13|rtv14|rtv141|rtv142|rtv15|rtv16|rtv17|a2ksem2) [--player N] [--window-ms N] [--fail-on-mismatch] [--text|--json]", Trait: TraitReadOnly, Input: "xsdat"},
	{Name: "replay spawns", Usage: "kit replay spawns <file.aoe2record> [--text]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay story", Usage: "kit replay story <file.aoe2record> [--context context.json] [--text|--brief]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay sync", Usage: "kit replay sync <file.aoe2record> [--checksums] [--raw-words] [--limit N] [--text|--json]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay sync-log", Usage: "kit replay sync-log <p0-sync.txt> [--replay file.aoe2record] [--limit N] [--text|--json]", Trait: TraitReadOnly, Input: "other"},
	{Name: "replay telemetry", Usage: "kit replay telemetry <file-or-folder> [--context context.json] [--schema telemetry.json] [--text]", Trait: TraitReadOnly, Input: "other"},
	{Name: "replay trigger-neighborhood", Usage: "kit replay trigger-neighborhood <file.aoe2record|zip> --trigger N [--depth N] [--limit N] [--text]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay triggers", Usage: "kit replay triggers <file.aoe2record|zip> [--grep TEXT] [--effect ID_OR_NAME] [--condition ID_OR_NAME] [--player N] [--variable N] [--unit-const ID] [--limit N] [--text]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "replay unknowns", Usage: "kit replay unknowns <folder> [--text]", Trait: TraitReadOnly, Input: "folder"},
	{Name: "replay xs-telemetry", Usage: "kit replay xs-telemetry <file.aoe2record> [--text]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "scen", Usage: "kit scen <blank|info|check|describe|settings|strings|refs|delete-plan|delete|disconnect|effects|glossary|idioms|analyze|triggers|trigger-neighborhood|audit-player-coverage|mechanic|trigger-flow|units|map|terrain|palette-usage|regions|verify|lint|xs|deploycheck|diff|diff-triggers|plan|patch|smoke|smoke-recipe> <file.aoe2scenario>", Trait: TraitReadOnly, Input: "group"},
	{Name: "scen analyze", Usage: "kit scen analyze <file.aoe2scenario>", Trait: TraitReadOnly, Input: "scenario"},
	{Name: "scen audit-player-coverage", Usage: "kit scen audit-player-coverage <file.aoe2scenario> [--players 1,2,3,4] [--text]", Trait: TraitReadOnly, Input: "scenario"},
	{Name: "scen blank", Usage: "kit scen blank <out.aoe2scenario> [--players N] [--human-slots N] [--timestamp UNIX] [--dummy-starters] [--dummy-unit UNIT_ID] [--dummy-origin X,Y] [--dummy-spacing N] [--gaia-active] [--keep-seed-triggers] [--text]", Trait: TraitWrites, Input: "none"},
	{Name: "scen deploycheck", Usage: "kit scen deploycheck <file.aoe2scenario> <deploy-tree> [--text] [--include-provisional]", Trait: TraitReadOnly, Input: "scenario"},
	{Name: "scen describe", Usage: "kit scen describe <file.aoe2scenario> [--section triggers|units|map|players|victory|messages|disables|ai|resources|all] [--full] [--json] [--no-path|--quiet-header]", Trait: TraitReadOnly, Input: "scenario"},
	{Name: "scen delete-plan", Usage: "kit scen delete-plan <file.aoe2scenario> <unit|trigger|variable|string> <id> [--text] | system-prefix <prefix> [--text] | unit-caption <caption> [--player N] [--text] | unit-caption-prefix <prefix> [--player N] [--text] | unit-caption-contains <text> [--player N] [--text] | unit-type <unit_const> [--player N] [--text] | units-player <player> [--text] | trigger-name <name> [--text] | trigger-prefix <prefix> [--text] | trigger-contains <text> [--text] | variable-name <name> [--text] | variable-prefix <prefix> [--text] | variable-contains <text> [--text] | string-text <exact_text> [--text] | string-prefix <prefix> [--text] | string-contains <text> [--text] | units-area <x1,y1,x2,y2> [--player N] [--unit N] [--text] | <effect|condition> <trigger_index>:<child_index> [--text] | <effect-type|condition-type> <type_id_or_name> [--trigger N|--trigger-prefix PREFIX] [--text] | effect-text-prefix <prefix> [--trigger N|--trigger-prefix PREFIX] [--text] | effect-text-contains <text> [--trigger N|--trigger-prefix PREFIX] [--text]", Trait: TraitReadOnly, Input: "scenario"},
	{Name: "scen delete", Usage: "kit scen delete <in.aoe2scenario> <out.aoe2scenario> <unit|trigger|variable|string> <id> | system-prefix <prefix> | unit-caption <caption> [--player N] | unit-caption-prefix <prefix> [--player N] | unit-caption-contains <text> [--player N] | unit-type <unit_const> [--player N] | units-player <player> | trigger-name <name> | trigger-prefix <prefix> | trigger-contains <text> | variable-name <name> | variable-prefix <prefix> | variable-contains <text> | string-text <exact_text> | string-prefix <prefix> | string-contains <text> | units-area <x1,y1,x2,y2> [--player N] [--unit N] | <effect|condition> <trigger_index>:<child_index> | <effect-type|condition-type> <type_id_or_name> [--trigger N|--trigger-prefix PREFIX] | effect-text-prefix <prefix> [--trigger N|--trigger-prefix PREFIX] | effect-text-contains <text> [--trigger N|--trigger-prefix PREFIX]", Trait: TraitWrites, Input: "scenario"},
	{Name: "scen disconnect", Usage: "kit scen disconnect <in.aoe2scenario> <out.aoe2scenario> <trigger|unit|variable|string> <id> | unit-caption <caption> [--player N] | unit-caption-prefix <prefix> [--player N] | unit-caption-contains <text> [--player N] | unit-type <unit_const> [--player N] | units-player <player> | trigger-name <name> | trigger-prefix <prefix> | trigger-contains <text> | variable-name <name> | variable-prefix <prefix> | variable-contains <text> | string-text <exact_text> | string-prefix <prefix> | string-contains <text> | units-area <x1,y1,x2,y2> [--player N] [--unit N]", Trait: TraitWrites, Input: "scenario"},
	{Name: "scen diff", Usage: "kit scen diff <before.aoe2scenario> <after.aoe2scenario> [--text|--json]", Trait: TraitReadOnly, Input: "scenario"},
	{Name: "scen diff-triggers", Usage: "kit scen diff-triggers <before.aoe2scenario> <after.aoe2scenario> [--limit N] [--text|--json]", Trait: TraitReadOnly, Input: "scenario"},
	{Name: "scen effects", Usage: "kit scen effects <file.aoe2scenario> [--raw|--census|--where EFFECT] [--limit N] [--max-mb N] [--text]", Trait: TraitReadOnly, Input: "scenario"},
	{Name: "scen glossary", Usage: "kit scen glossary <file.aoe2scenario> [--limit N] [--max-mb N] [--text]", Trait: TraitReadOnly, Input: "scenario"},
	{Name: "scen idioms", Usage: "kit scen idioms <file.aoe2scenario> [--text]", Trait: TraitReadOnly, Input: "scenario"},
	{Name: "scen lint", Usage: "kit scen lint <file.aoe2scenario> [--text] [--include-provisional]", Trait: TraitReadOnly, Input: "scenario"},
	{Name: "scen mechanic", Usage: "kit scen mechanic <file.aoe2scenario> --kind garrison-token|transform-toggle|teleport-transition|refresh-cycle [--grep TEXT] [--text]", Trait: TraitReadOnly, Input: "scenario"},
	{Name: "scen patch", Usage: "kit scen patch <in.aoe2scenario> <out.aoe2scenario> --recipe recipe.json", Trait: TraitWrites, Input: "scenario"},
	{Name: "scen plan", Usage: "kit scen plan <in.aoe2scenario> --recipe recipe.json", Trait: TraitWrites, Input: "scenario"},
	{Name: "scen smoke", Usage: "kit scen smoke <in.aoe2scenario> <out.aoe2scenario> [--x N] [--y N] [--player N] [--unit N] [--terrain N] [--elevation N] [--layer N]", Trait: TraitWrites, Input: "scenario"},
	{Name: "scen smoke-recipe", Usage: "kit scen smoke-recipe [--x N] [--y N] [--player N] [--unit N] [--terrain N] [--elevation N] [--layer N]", Trait: TraitReadOnly, Input: "none"},
	{Name: "scen refs", Usage: "kit scen refs <file.aoe2scenario> [--kind unit|trigger|variable|string|all] [--id N] [--text]", Trait: TraitReadOnly, Input: "scenario"},
	{Name: "scen settings", Usage: "kit scen settings <file.aoe2scenario> [--text|--json]", Trait: TraitReadOnly, Input: "scenario"},
	{Name: "scen strings", Usage: "kit scen strings <file.aoe2scenario>", Trait: TraitReadOnly, Input: "scenario"},
	{Name: "scen terrain", Usage: "kit scen terrain <file.aoe2scenario> [--id N] [--tiles] [--text|--json]", Trait: TraitReadOnly, Input: "scenario"},
	{Name: "scen palette-usage", Usage: "kit scen palette-usage <file.aoe2scenario> --dat <empires*.dat> [--json|--text]", Trait: TraitReadOnly, Input: "scenario"},
	{Name: "scen trigger-flow", Usage: "kit scen trigger-flow <file.aoe2scenario> (--grep TEXT|--unit-ref ID|--variable N) [--limit N] [--text]", Trait: TraitReadOnly, Input: "scenario"},
	{Name: "scen trigger-neighborhood", Usage: "kit scen trigger-neighborhood <file.aoe2scenario> (--trigger N|--unit-ref ID|--variable N) [--depth N] [--limit N] [--text]", Trait: TraitReadOnly, Input: "scenario"},
	{Name: "scen triggers", Usage: "kit scen triggers <file.aoe2scenario> [--grep TEXT] [--effect ID_OR_NAME] [--condition ID_OR_NAME] [--message TEXT] [--unit-ref ID] [--unit-type ID] [--player N] [--variable N] [--area x1,y1,x2,y2] [--limit N] [--max-mb N] [--text|--json]", Trait: TraitReadOnly, Input: "scenario"},
	{Name: "scen units", Usage: "kit scen units <file.aoe2scenario> [--named]", Trait: TraitReadOnly, Input: "scenario"},
	{Name: "scen xs", Usage: "kit scen xs <file.aoe2scenario> [--deploy-tree dir] [--text|--json]", Trait: TraitReadOnly, Input: "scenario"},
	{Name: "scen xs attach", Usage: "kit scen xs attach <in.aoe2scenario> <out.aoe2scenario> --xs file.xs [--name Entry.xs] [--also-carrier] [--title TITLE] [--trigger-name NAME] [--text|--json]", Trait: TraitWrites, Input: "scenario"},
	{Name: "scen xs deploy", Usage: "kit scen xs deploy <file.aoe2scenario> <deploy-tree> [--name Entry.xs] [--carrier N|--trigger N] [--force] [--check] [--text|--json]", Trait: TraitWrites, Input: "scenario"},
	{Name: "scen xs embed", Usage: "kit scen xs embed <in.aoe2scenario> <out.aoe2scenario> --xs file.xs [--title TITLE] [--trigger-name NAME] [--replace-trigger N] [--append] [--keep-attachment] [--text|--json]", Trait: TraitWrites, Input: "scenario"},
	{Name: "scen xs extract", Usage: "kit scen xs extract <file.aoe2scenario> --out file.xs [--carrier N|--trigger N] [--force] [--text|--json]", Trait: TraitWrites, Input: "scenario"},
	{Name: "scen xs compare", Usage: "kit scen xs compare <file.aoe2scenario> <file.xs> [--carrier N|--trigger N] [--text|--json]", Trait: TraitReadOnly, Input: "scenario"},
	{Name: "scen write-check", Usage: "kit scen write-check <before.aoe2scenario> <after.aoe2scenario> [--text|--json] [--include-provisional]", Trait: TraitReadOnly, Input: "scenario"},
	{Name: "summary", Usage: "kit summary [folder]", Trait: TraitReadOnly, Input: "folder"},
	{Name: "swatch patterns", Usage: "kit swatch patterns <list|summary|validate|json>", Trait: TraitReadOnly, Input: "group"},
	{Name: "verify", Usage: "kit verify [folder] [--go-checks]", Trait: TraitReadOnly, Input: "folder"},
	{Name: "verify-run", Usage: "kit verify-run <replay.aoe2record|replay.zip> --contract contract.json [--text]", Trait: TraitReadOnly, Input: "replay"},
	{Name: "version", Usage: "kit version", Trait: TraitReadOnly, Input: "none"},
	{Name: "xs bridge", Usage: "kit xs bridge <variables.json> [--out-dir DIR]", Trait: TraitWrites, Input: "other"},
	{Name: "xs datagen", Usage: "kit xs datagen <arrays.json> [--out module.xs]", Trait: TraitWrites, Input: "other"},
	{Name: "xs inspect", Usage: "kit xs inspect <file.xsdat> [--types string,int,...] [--text]", Trait: TraitReadOnly, Input: "xsdat"},
	{Name: "xs shims", Usage: "kit xs shims <file-or-dir>... [--out recipe.json] [--prefix TEXT] [--enabled] [--include-params]", Trait: TraitWrites, Input: "other"},
	{Name: "xsdat decode", Usage: "kit xsdat decode <file.xsdat> [--types string,int,...] [--ledger expected.json] [--schema rtv12|rtv13|rtv14|rtv141|rtv142|rtv15|rtv16|rtv17|a2ksem2] [--text]", Trait: TraitReadOnly, Input: "xsdat"},
}
