package xs

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
)

type DatagenSpec struct {
	Function string         `json:"function"`
	Arrays   []DatagenArray `json:"arrays"`
	Includes []string       `json:"includes,omitempty"`
	Metadata map[string]any `json:"metadata,omitempty"`
}

type DatagenArray struct {
	Name    string            `json:"name"`
	Type    string            `json:"type"`
	Default json.RawMessage   `json:"default,omitempty"`
	Values  []json.RawMessage `json:"values"`
}

type DatagenReport struct {
	Verification VerificationClaim `json:"verification"`
	Function     string            `json:"function"`
	Arrays       []DatagenSummary  `json:"arrays"`
	XSModule     string            `json:"xs_module"`
	Verified     bool              `json:"verified"`
}

type DatagenSummary struct {
	Name   string `json:"name"`
	Type   string `json:"type"`
	Count  int    `json:"count"`
	Handle string `json:"handle"`
}

func LoadDatagenSpec(path string) (DatagenSpec, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return DatagenSpec{}, err
	}
	var spec DatagenSpec
	if err := json.Unmarshal(data, &spec); err != nil {
		return DatagenSpec{}, err
	}
	return spec, nil
}

func GenerateDatagen(spec DatagenSpec) (DatagenReport, error) {
	if spec.Function == "" {
		spec.Function = "a2k_generated_init_arrays"
	}
	if err := validateIdentifier(spec.Function); err != nil {
		return DatagenReport{}, fmt.Errorf("function: %w", err)
	}
	if len(spec.Arrays) == 0 {
		return DatagenReport{}, fmt.Errorf("datagen spec has no arrays")
	}
	seen := map[string]bool{}
	arrays := append([]DatagenArray(nil), spec.Arrays...)
	sort.SliceStable(arrays, func(i, j int) bool { return arrays[i].Name < arrays[j].Name })
	for _, array := range arrays {
		if err := validateIdentifier(array.Name); err != nil {
			return DatagenReport{}, fmt.Errorf("array %q: %w", array.Name, err)
		}
		if seen[array.Name] {
			return DatagenReport{}, fmt.Errorf("duplicate array name %q", array.Name)
		}
		seen[array.Name] = true
		if _, _, err := xsArrayType(array.Type); err != nil {
			return DatagenReport{}, fmt.Errorf("array %q: %w", array.Name, err)
		}
	}
	module, summaries, err := renderDatagenXS(spec.Function, spec.Includes, arrays)
	if err != nil {
		return DatagenReport{}, err
	}
	return DatagenReport{
		Verification: StructureVerifiedClaim("Generated xsArray initialization module round-tripped from JSON counts and value types; engine execution still requires an in-game XS run."),
		Function:     spec.Function,
		Arrays:       summaries,
		XSModule:     module,
		Verified:     true,
	}, nil
}

func WriteDatagenModule(report DatagenReport, output string) error {
	if output == "" {
		return nil
	}
	return os.WriteFile(output, []byte(report.XSModule), 0o644)
}

func renderDatagenXS(function string, includes []string, arrays []DatagenArray) (string, []DatagenSummary, error) {
	var b strings.Builder
	b.WriteString("// Generated by AoE2Kit from structured JSON.\n")
	for _, include := range includes {
		if strings.Contains(include, "\"") {
			return "", nil, fmt.Errorf("include path contains quote: %q", include)
		}
		fmt.Fprintf(&b, "include \"%s\";\n", include)
	}
	if len(includes) > 0 {
		b.WriteString("\n")
	}
	summaries := make([]DatagenSummary, 0, len(arrays))
	for _, array := range arrays {
		handle := array.Name
		fmt.Fprintf(&b, "extern int %s = -1;\n", handle)
		summaries = append(summaries, DatagenSummary{Name: array.Name, Type: normalizedArrayType(array.Type), Count: len(array.Values), Handle: handle})
	}
	b.WriteString("\n")
	fmt.Fprintf(&b, "void %s() {\n", function)
	for _, array := range arrays {
		kind := normalizedArrayType(array.Type)
		createSuffix, setSuffix, err := xsArrayType(kind)
		if err != nil {
			return "", nil, err
		}
		defaultValue, err := xsLiteral(kind, array.Default, true)
		if err != nil {
			return "", nil, fmt.Errorf("array %q default: %w", array.Name, err)
		}
		fmt.Fprintf(&b, "    %s = xsArrayCreate%s(%d, %s, \"%s\");\n", array.Name, createSuffix, len(array.Values), defaultValue, array.Name)
		for i, raw := range array.Values {
			value, err := xsLiteral(kind, raw, false)
			if err != nil {
				return "", nil, fmt.Errorf("array %q value %d: %w", array.Name, i, err)
			}
			fmt.Fprintf(&b, "    xsArraySet%s(%s, %d, %s);\n", setSuffix, array.Name, i, value)
		}
	}
	b.WriteString("}\n")
	return b.String(), summaries, nil
}

func xsArrayType(kind string) (string, string, error) {
	switch normalizedArrayType(kind) {
	case "int":
		return "Int", "Int", nil
	case "float":
		return "Float", "Float", nil
	case "bool":
		return "Bool", "Bool", nil
	case "string":
		return "String", "String", nil
	default:
		return "", "", fmt.Errorf("unsupported type %q; supported: int, float, bool, string", kind)
	}
}

func normalizedArrayType(kind string) string {
	switch strings.ToLower(strings.TrimSpace(kind)) {
	case "integer", "s32":
		return "int"
	case "f32", "double":
		return "float"
	case "boolean":
		return "bool"
	default:
		return strings.ToLower(strings.TrimSpace(kind))
	}
}

func xsLiteral(kind string, raw json.RawMessage, defaultForKind bool) (string, error) {
	if len(raw) == 0 || string(raw) == "null" {
		if !defaultForKind {
			return "", fmt.Errorf("missing value")
		}
		switch kind {
		case "int":
			return "0", nil
		case "float":
			return "0.0", nil
		case "bool":
			return "false", nil
		case "string":
			return "\"\"", nil
		}
	}
	switch kind {
	case "int":
		var value int
		if err := json.Unmarshal(raw, &value); err != nil {
			return "", err
		}
		return strconv.Itoa(value), nil
	case "float":
		var value float64
		if err := json.Unmarshal(raw, &value); err != nil {
			return "", err
		}
		return strconv.FormatFloat(value, 'f', -1, 64), nil
	case "bool":
		var value bool
		if err := json.Unmarshal(raw, &value); err != nil {
			return "", err
		}
		if value {
			return "true", nil
		}
		return "false", nil
	case "string":
		var value string
		if err := json.Unmarshal(raw, &value); err != nil {
			return "", err
		}
		return strconv.Quote(value), nil
	default:
		return "", fmt.Errorf("unsupported type %q", kind)
	}
}
